# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'SnoKE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'TextFieldEffects’, :git => 'https://github.com/raulriera/TextFieldEffects.git'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'

end
